-- Pack QCM : 50 questions cinema d'auteur
begin;

insert into public.questions (
  id,
  difficulty,
  prompt,
  answer,
  accepted_answers,
  metadata,
  is_active
)
values
  ('cin-001', 'easy', 'Dans "In the Mood for Love", quel élément visuel récurrent symbolise le passage du temps et l''enfermement des sentiments ?', 'Les robes (Qipao) portées par Maggie Cheung.', jsonb_build_array('Les robes (Qipao) portées par Maggie Cheung.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('La pluie incessante sur les toits de Londres.', 'Le changement de couleur des murs de l''appartement.', 'L''utilisation systématique de ralentis en noir et blanc.')), true),
  ('cin-002', 'easy', 'Quel est le thème central du film "Le Septième Sceau" d''Ingmar Bergman ?', 'Le silence de Dieu face à la mort.', jsonb_build_array('Le silence de Dieu face à la mort.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('La conquête des Amériques par les Croisés.', 'Une romance interdite pendant la Renaissance.', 'La survie d''un groupe de paysans face à une invasion viking.')), true),
  ('cin-003', 'easy', 'Dans quel film de David Lynch une mystérieuse boîte bleue sert-elle de pivot narratif ?', 'Mulholland Drive', jsonb_build_array('Mulholland Drive'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Lost Highway', 'Blue Velvet', 'Eraserhead')), true),
  ('cin-004', 'easy', 'Quel cinéaste français est l''auteur de "Les Quatre Cents Coups" ?', 'François Truffaut', jsonb_build_array('François Truffaut'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Jean-Luc Godard', 'Claude Chabrol', 'Eric Rohmer')), true),
  ('cin-005', 'easy', 'Quel film de Bong Joon-ho a marqué l''histoire en étant le premier film non-anglophone à gagner l''Oscar du Meilleur Film ?', 'Parasite', jsonb_build_array('Parasite'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Memories of Murder', 'The Host', 'Okja')), true),
  ('cin-006', 'easy', 'Dans "Old Boy" de Park Chan-wook, combien d''années le protagoniste reste-t-il séquestré ?', '15 ans', jsonb_build_array('15 ans'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('10 ans', '20 ans', '5 ans')), true),
  ('cin-007', 'easy', 'Quel est le trait distinctif du film "La Passion de Jeanne d''Arc" (1928) de Dreyer ?', 'L''usage intensif et révolutionnaire des gros plans.', jsonb_build_array('L''usage intensif et révolutionnaire des gros plans.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('C''est le premier film en couleur de l''histoire.', 'Il contient des scènes de batailles épiques avec des milliers de figurants.', 'Le film est entièrement tourné en vue subjective.')), true),
  ('cin-008', 'easy', 'Quel réalisateur est célèbre pour ses caméos systématiques dans ses propres films ?', 'Alfred Hitchcock', jsonb_build_array('Alfred Hitchcock'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Stanley Kubrick', 'Orson Welles', 'Andrei Tarkovski')), true),
  ('cin-009', 'easy', 'Dans quel film suit-on la déambulation d''une chanteuse dans Paris en attendant des résultats médicaux ?', 'Cléo de 5 à 7', jsonb_build_array('Cléo de 5 à 7'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('À bout de souffle', 'Vivre sa vie', 'L''une chante, l''autre pas')), true),
  ('cin-010', 'easy', 'Quel film de SF d''auteur met en scène une Scarlett Johansson "extra-terrestre" chassant des hommes en Écosse ?', 'Under the Skin', jsonb_build_array('Under the Skin'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Her', 'Ex Machina', 'Annihilation')), true),

  ('cin-011', 'medium', 'Dans "Stalker" de Tarkovski, qu''est-ce que "La Zone" est censée abriter en son centre ?', 'Une chambre qui exauce les vœux les plus sincères.', jsonb_build_array('Une chambre qui exauce les vœux les plus sincères.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Un portail vers une dimension parallèle peuplée de monstres.', 'Une arme nucléaire oubliée par le gouvernement.', 'Le dernier arbre vivant de la planète.')), true),
  ('cin-012', 'medium', 'Quelle est la particularité technique du film "La Jetée" de Chris Marker ?', 'Il est presque entièrement composé de photographies fixes.', jsonb_build_array('Il est presque entièrement composé de photographies fixes.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Il a été tourné sans caméra, uniquement par montage d''archives.', 'C''est le premier film tourné intégralement sous l''eau.', 'Il ne comporte aucun montage, c''est un seul plan-séquence de 30 minutes.')), true),
  ('cin-013', 'medium', 'Dans "L''Ange Exterminateur", qu''est-ce qui empêche les invités de sortir de la pièce ?', 'Rien de physique, c''est un blocage psychologique inexplicable.', jsonb_build_array('Rien de physique, c''est un blocage psychologique inexplicable.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('La porte est verrouillée de l''extérieur par un tueur.', 'Une épidémie de peste noire à l''extérieur de la maison.', 'Un champ de force électromagnétique expérimental.')), true),
  ('cin-014', 'medium', 'Quel film de Michael Haneke met en scène une famille prise en otage par deux jeunes gens en gants blancs ?', 'Funny Games', jsonb_build_array('Funny Games'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Caché', 'Le Ruban Blanc', 'La Pianiste')), true),
  ('cin-015', 'medium', 'Quel réalisateur a dirigé "The Lobster", où les célibataires sont transformés en animaux s''ils ne trouvent pas de partenaire ?', 'Yorgos Lanthimos', jsonb_build_array('Yorgos Lanthimos'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Lars von Trier', 'Ari Aster', 'Ruben Östlund')), true),
  ('cin-016', 'medium', 'Quel film d''animation de Satoshi Kon traite du flou entre réalité et fiction pour une idole de la J-Pop ?', 'Perfect Blue', jsonb_build_array('Perfect Blue'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Paprika', 'Millennium Actress', 'Tokyo Godfathers')), true),
  ('cin-017', 'medium', 'Dans "Blow-Up" d''Antonioni, que croit découvrir le photographe en agrandissant ses clichés ?', 'Un cadavre caché dans un parc.', jsonb_build_array('Un cadavre caché dans un parc.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Une preuve d''adultère de sa propre femme.', 'Le visage d''un espion soviétique.', 'Une soucoupe volante survolant Londres.')), true),
  ('cin-018', 'medium', 'Lequel de ces films n''appartient pas à la "Trilogie des couleurs" de Kieślowski ?', 'Vert', jsonb_build_array('Vert'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Bleu', 'Blanc', 'Rouge')), true),
  ('cin-019', 'medium', 'Quel est le métier du protagoniste dans "Le Samouraï" de Jean-Pierre Melville ?', 'Tueur à gages', jsonb_build_array('Tueur à gages'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Policier infiltré', 'Voleur de bijoux', 'Garde du corps')), true),
  ('cin-020', 'medium', 'Quel réalisateur est connu pour l''usage systématique d''acteurs maquillés en blanc et de plans fixes dans sa trilogie "Nous, les vivants" ?', 'Roy Andersson', jsonb_build_array('Roy Andersson'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Aki Kaurismäki', 'Béla Tarr', 'Lars von Trier')), true),
  ('cin-021', 'medium', 'Dans "Enter the Void", comment la caméra est-elle principalement positionnée ?', 'En vue subjective (POV) puis flottant au-dessus des décors.', jsonb_build_array('En vue subjective (POV) puis flottant au-dessus des décors.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Uniquement au niveau du sol (contre-plongée totale).', 'Elle est fixe durant tout le film.', 'C''est un montage d''images de vidéo-surveillance.')), true),
  ('cin-022', 'medium', 'Quel film de Pier Paolo Pasolini adapte de manière crue et politique l''œuvre du Marquis de Sade ?', 'Salo ou les 120 journées de Sodome', jsonb_build_array('Salo ou les 120 journées de Sodome'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Le Décaméron', 'L''Évangile selon saint Matthieu', 'Théorème')), true),
  ('cin-023', 'medium', 'Quelle est la particularité du film "Soy Cuba" (1964) de Kalatozov ?', 'Ses mouvements de caméra virtuoses et techniquement impossibles pour l''époque.', jsonb_build_array('Ses mouvements de caméra virtuoses et techniquement impossibles pour l''époque.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Il a été tourné entièrement sans pellicule.', 'C''est une comédie musicale muette.', 'Il utilise des acteurs qui ne parlent que par métaphores.')), true),
  ('cin-024', 'medium', 'Dans "Pickpocket" de Robert Bresson, quelle est l''obsession du personnage principal ?', 'La perfection du geste technique du vol.', jsonb_build_array('La perfection du geste technique du vol.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Venger la mort de sa mère.', 'Devenir le plus grand prestidigitateur de Paris.', 'Échapper à une malédiction familiale.')), true),
  ('cin-025', 'medium', 'Quel film de Gaspar Noé commence par la fin et remonte le temps de manière chronologique inversée ?', 'Irréversible', jsonb_build_array('Irréversible'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Climax', 'Seul contre tous', 'Love')), true),
  ('cin-026', 'medium', 'Quel réalisateur a filmé "Portrait de la jeune fille en feu" ?', 'Céline Sciamma', jsonb_build_array('Céline Sciamma'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Alice Diop', 'Mia Hansen-Løve', 'Julia Ducournau')), true),
  ('cin-027', 'medium', 'Dans "Persona" d''Ingmar Bergman, quelle relation lie les deux femmes protagonistes ?', 'Une infirmière et sa patiente qui a cessé de parler.', jsonb_build_array('Une infirmière et sa patiente qui a cessé de parler.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Deux sœurs jumelles séparées à la naissance.', 'Une mère et sa fille en voyage.', 'Deux espionnes ennemies.')), true),
  ('cin-028', 'medium', 'De quel pays est originaire le film "Hana-bi" (Feux d''artifice) de Takeshi Kitano ?', 'Japon', jsonb_build_array('Japon'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Corée du Sud', 'Chine', 'Taïwan')), true),
  ('cin-029', 'medium', 'Quel film de SF d''auteur est célèbre pour sa scène d''ouverture avec un os se transformant en vaisseau spatial ?', '2001, l''Odyssée de l''espace', jsonb_build_array('2001, l''Odyssée de l''espace'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Solaris', 'Blade Runner', 'Interstellar')), true),
  ('cin-030', 'medium', 'Dans "Le Miroir" de Tarkovski, comment sont structurés les souvenirs ?', 'De manière non-linéaire, mêlant archives, rêves et poésie.', jsonb_build_array('De manière non-linéaire, mêlant archives, rêves et poésie.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Par ordre alphabétique des lieux visités.', 'Selon une enquête policière classique.', 'C''est un long flashback unique.')), true),

  ('cin-031', 'hard', 'Dans "Sátántangó" de Béla Tarr, quelle est la durée moyenne des plans-séquences ?', 'Environ 10 minutes', jsonb_build_array('Environ 10 minutes'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('30 secondes', '2 minutes', '30 minutes')), true),
  ('cin-032', 'hard', 'Quel film de Chantal Akerman montre pendant plusieurs minutes une femme faire un pain de viande ?', 'Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles', jsonb_build_array('Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('News from Home', 'Golden Eighties', 'La Captive')), true),
  ('cin-033', 'hard', 'Dans "La Montagne Sacrée" de Jodorowsky, que transforme l''alchimiste au début du film ?', 'Des excréments en or.', jsonb_build_array('Des excréments en or.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Du plomb en vin.', 'Des cadavres en fleurs.', 'Du sable en diamants.')), true),
  ('cin-034', 'hard', 'Quel est le titre du film inachevé et maudit d''Andrzej Żuławski sur une civilisation lunaire ?', 'Sur le globe d''argent', jsonb_build_array('Sur le globe d''argent'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Possession', 'La Diagonale du fou', 'Le Troisième Monde')), true),
  ('cin-035', 'hard', 'Lequel de ces films n''a aucun dialogue pendant ses 20 premières minutes ?', 'Il est difficile d''être un dieu', jsonb_build_array('Il est difficile d''être un dieu'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('An Elephant Sitting Still', 'Burning', 'Le Cheval de Turin')), true),
  ('cin-036', 'hard', 'Quelle est la particularité visuelle du film "Begotten" (1989) d''E. Elias Merhige ?', 'Une image en noir et blanc ultra-contrastée et dégradée, presque illisible.', jsonb_build_array('Une image en noir et blanc ultra-contrastée et dégradée, presque illisible.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Il est filmé à travers un bocal de poisson.', 'Toutes les scènes sont filmées à l''envers.', 'Le film est projeté sur de la vapeur d''eau.')), true),
  ('cin-037', 'hard', 'Dans "L''Homme qui dort" (1974) de Bernard Queysanne, quelle est la spécificité narrative ?', 'Il n''y a aucun dialogue, seulement une voix-off à la deuxième personne (tu).', jsonb_build_array('Il n''y a aucun dialogue, seulement une voix-off à la deuxième personne (tu).'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Le film est raconté par un chat.', 'Le protagoniste parle une langue inventée.', 'Il n''y a aucun son du début à la fin.')), true),
  ('cin-038', 'hard', 'Quel film expérimental de 1967 consiste en un seul zoom de 45 minutes vers une photographie ?', 'Wavelength', jsonb_build_array('Wavelength', 'Wavelength (Michael Snow)'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Empire', 'Sleep', 'Zorns Lemma')), true),
  ('cin-039', 'hard', 'Quel réalisateur géorgien a conçu "La Couleur de la grenade" comme une série d''icônes vivantes ?', 'Sergueï Paradjanov', jsonb_build_array('Sergueï Paradjanov'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Tenguiz Abouladzé', 'Otar Iosseliani', 'Elem Klimov')), true),
  ('cin-040', 'hard', 'Dans "Tropical Malady", quel changement radical s''opère à la moitié du film ?', 'Le film devient une traque mystique dans la jungle sans lien narratif direct avec le début.', jsonb_build_array('Le film devient une traque mystique dans la jungle sans lien narratif direct avec le début.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Le film passe de la couleur au noir et blanc.', 'Les acteurs principaux changent de sexe.', 'L''histoire recommence mais du point de vue de l''antagoniste.')), true),
  ('cin-041', 'hard', 'Quel film de Jean Eustache est un monument du "cinéma de la parole" de 3h40 ?', 'La Maman et la Putain', jsonb_build_array('La Maman et la Putain'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Mes petites amoureuses', 'Le Père Noël a les yeux bleus', 'Numéro Zéro')), true),
  ('cin-042', 'hard', 'Quel réalisateur a tourné "Le Cheval de Turin", censé être son dernier film, sur la fin du monde et la répétition ?', 'Béla Tarr', jsonb_build_array('Béla Tarr'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('László Nemes', 'Kornél Mundruczó', 'Ildikó Enyedi')), true),
  ('cin-043', 'hard', 'Dans "Eraserhead", que représente le "bébé" du protagoniste Henry ?', 'Une créature mutante et informe qui ne cesse de pleurer.', jsonb_build_array('Une créature mutante et informe qui ne cesse de pleurer.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Un enfant tout à fait normal que Henry imagine monstrueux.', 'Un automate créé pour remplacer un fils décédé.', 'Un simple sac de farine.')), true),
  ('cin-044', 'hard', 'Lequel de ces réalisateurs est le pionnier du "Cinéma Novo" brésilien ?', 'Glauber Rocha', jsonb_build_array('Glauber Rocha'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Nelson Pereira dos Santos', 'Walter Salles', 'Fernando Meirelles')), true),
  ('cin-045', 'hard', 'Quel film d''Abbas Kiarostami suit une conversation en voiture dans les rues de Téhéran via 10 plans fixes ?', 'Ten', jsonb_build_array('Ten'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Le Goût de la cerise', 'Le vent nous emportera', 'Copie conforme')), true),
  ('cin-046', 'hard', 'Dans "Hard to Be a God" d''Alexeï Guerman, quel est l''aspect le plus marquant de la mise en scène ?', 'L''immondice, la boue et le chaos organique omniprésents à l''écran.', jsonb_build_array('L''immondice, la boue et le chaos organique omniprésents à l''écran.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('L''utilisation de maquettes en papier mâché.', 'Le film est tourné uniquement à la bougie.', 'Tous les acteurs portent des masques d''animaux.')), true),
  ('cin-047', 'hard', 'Quel film de Kaneto Shindō est quasi-muet et montre un couple transporter de l''eau sur une île aride ?', 'L''Île nue', jsonb_build_array('L''Île nue'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Onibaba', 'Kuroneko', 'Le Trou')), true),
  ('cin-048', 'hard', 'Quel réalisateur a filmé "An Elephant Sitting Still" avant de se suicider à 29 ans ?', 'Hu Bo', jsonb_build_array('Hu Bo'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Bi Gan', 'Jia Zhangke', 'Wang Bing')), true),
  ('cin-049', 'hard', 'Dans "Possession" de Żuławski, quelle est la nature de la créature avec laquelle Isabelle Adjani a une liaison ?', 'Un monstre tentaculaire qui prend peu à peu forme humaine.', jsonb_build_array('Un monstre tentaculaire qui prend peu à peu forme humaine.'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Une projection mentale de son mari.', 'Un démon invisible.', 'Son propre reflet dans le miroir.')), true),
  ('cin-050', 'hard', 'Quel cinéaste taïwanais a réalisé "Goodbye, Dragon Inn", un film sur la dernière séance d''un cinéma qui ferme ?', 'Tsai Ming-liang', jsonb_build_array('Tsai Ming-liang'), jsonb_build_object('source', 'cinema-auteur-qcm', 'template', 'manual-mcq', 'answerMode', 'mcq', 'distractors', jsonb_build_array('Edward Yang', 'Hou Hsiao-hsien', 'Ang Lee')), true)
on conflict (id) do update set
  difficulty = excluded.difficulty,
  prompt = excluded.prompt,
  answer = excluded.answer,
  accepted_answers = excluded.accepted_answers,
  metadata = excluded.metadata,
  is_active = excluded.is_active;

commit;
